### PR TITLE
Issue #1: Some local variables were mistakenly global, fix some typos.

### PR DESCRIPTION
**Pull request by rdawemsys**
Using our fork of [lualint](https://github.com/MessageSystems/lualint), I found a few variables that were not defined as local. Some of them were global variables that should be locals, and some were typos.

I've done some basic testing of these using SQS (some of our code), S3 and EC2 (test/s3.lua and test/ec2.lua). I could not completely run the S3 tests in our environment.

### CODE REVIEW

**Comment by umegaya** [comment]
hi, thank you for fixing my messy code. I will execute all the test, and confirm working correctly (s3 bucket name is taken by someone else, so I fix it to make tmp name). also code seems no problem, I will merge it.

**Comment by rdawemsys** [comment]
Ah, I had the "lua-aws-test" bucket in the AWS account I was using. I have deleted it now.

**Comment by umegaya** [comment]
@rdawemsys thank you for taking care about bucket name, but I think its better to use tmp name because other guy may accidentally take that name. I have fixed it by #26.

**Comment by rdawemsys** [comment]
Good idea, thanks!

**Pull request merged**
