### PR TITLE
Update API Specs from `aws-sdk-js`

### LINKED ISSUE #72: Missing `Layers` in when creating a Lambda Function
I am not able to create a function with `Layers` defined. I think the issue is that the spec is from 2015 and was last updated in #55.

For example, I see [`MemorySize`](https://github.com/umegaya/lua-aws/blob/bd881ebdd78a0453f8d7e264eb9f2d3c4331fd37/lua-aws/services/specs/lambda-2015-03-31.normal.json#L860) but not `Layers`.

The the [javascript SDK](https://docs.aws.amazon.com/AWSJavaScriptSDK/latest/AWS/Lambda.html#createFunction-property) and the [CreateFunction API](https://docs.aws.amazon.com/lambda/latest/dg/API_CreateFunction.html#SSS-CreateFunction-request-Layers) says that `Layers` is an optional  array of strings.

Is it possible to update `lua-aws` to support layers?

### PR DESCRIPTION
**Pull request by styfle**
This is an attempt to fix #72 

Source: https://github.com/aws/aws-sdk-js/tree/master/apis

### CODE REVIEW

**Comment by umegaya** [comment]
thank you for contributing lua-aws!! I will check detail in this weekend :)

**Comment by styfle** [comment]
Thanks for taking a look!

Let me know if you want me to delete the `normal.json` files.

**Comment by umegaya** [comment]
hmm, seems my test is broken due to environment change. 
merging this fix to master is urgent? if not, I want to merge this after fix my test and confirm this PR breaks nothing (after a few days, I can have my free time again).

for normal.json things, I want to keep them for now. because original repo still contains these https://github.com/aws/aws-sdk-js/tree/master/apis

**Comment by styfle** [comment]
@umegaya Oh I didn't look at the repo, I was looking at the files published to npm.

I pushed an update with the source files from `aws-sdk-js` repo which contains the `normal.json` files.

How does that look?

**Comment by umegaya** [comment]
seems great 👍  but please wait for merging.

**Comment by styfle** [comment]
@umegaya Thanks! Do you think it would be possible to setup GitHub Actions CI to run the tests for each PR? Maybe something like [lua-action](https://github.com/MilesChou/lua-action) might work?

**Comment by styfle** [comment]
Hmm, I'm getting an error too.

Is this what you are seeing?

```lua
{
  code = "SerializationException",
  message = "Start of structure or map found where not expected."
}
```

**Comment by umegaya** [comment]
which API call causes the error? seems [shape](https://github.com/umegaya/lua-aws/tree/master/lua-aws/shape) related problem, shape maps API parameters into proper http request component (some parameter embedded into url path, another parameter put to post body, etc. ), otherwise request payload broken.

**Comment by styfle** [comment]
This was `aws.Lambda.CreateFunction()`

**Comment by umegaya** [comment]
@styfle hi, sorry for delay, I opened #74 to fix broken tests and add github actions to run test, in addition to the change set of this PR, I think its ready to merge. 

> This was aws.Lambda.CreateFunction()

that error is strange, because my test https://github.com/umegaya/lua-aws/blob/master/test/lambda.lua#L60 is pass with no problem. 

if possible, could you post zip files and usage sample of `aws.Lambda.CreateFunction` which causes error?

**Comment by umegaya** [comment]
if testcase canot not be available (or no response in a few days), I will merge #74 instead of the PR.

**Comment by styfle** [comment]
You need to add `Layers = ["arn:aws:lambda:::awslayer:AmazonLinux2"]` and use this: [rust.zip](https://github.com/umegaya/lua-aws/files/4277488/rust.zip)

**Comment by styfle** [comment]
@umegaya I was mistaken.

It works fine when passing `Layers = {"arn:aws:lambda:::awslayer:AmazonLinux2"}`.

The bug I was experiencing was when I attempted to assign the empty array `Layers = {}`. The API didn't like that. So instead I used undefined and it works!

This should PR should be good to merge 👍

**Pull request merged**
