### PR TITLE
Updated code to work in windows and added reference to a bit library …

### PR DESCRIPTION
**Pull request by aryajur**
…in the readme

### CODE REVIEW

**Comment by umegaya** [comment]
hi, sorry for delay, I took vacation :< 
thank you for your work! code seems ok, and test passes on osx. 

but actually after adding your modification, lua-aws does not refer your library (aryajur/bit) at all. 
do you want to add the link for your library (aryajur/bit) to README as tips for lua 5.3 users (I think they lost standard bit library)? 

if so, I will create new section "for lua 5.3 users" to separate compatibility issue, rather than adding unused library to the list of external libs.

**Comment by aryajur** [comment]
hi,
    yes the bit library is gone in 5.3 now bit operators are there. So yes making a 5.3 section is a good idea.

**Comment by umegaya** [comment]
ok, so I merge this and then modify README. thank you for response!

**Comment by aryajur** [comment]
Thank you!

**Pull request merged**
