### PR TITLE
alternate way to adding rockspec

### PR DESCRIPTION
**Pull request by umegaya**
refs #11
I check PR from https://github.com/CriztianiX/lua-aws, there is two points to discuss.
the purpose of this PR is describe my opinion about these points with working implementation.

1. we should treat dkjson as external dependency?
 - if we obey the standard way of luarocks, dkjson should be treat as external dependency because it has entry in luarocks. 
 - but it means that potentially lua-aws have to support multiple version of dkjson, also any kind of project-specific modification to dkjson is not allowed. 
 - so I prefer to maintain dkjson's version by ourselves for better flexibility and maintainability. 

2. how we provide json AWS REST API definition files?
 - in AWS_Service.build_api, util.script_path change to util.service_path which returns static path string by changes made in #11. 
 - if I understand correctly, this is because there is no standard way to install lua-aws/services/definitions/*.json to /usr/local/share/lua/5.1/lua-aws/services/definitions/
 - but luarocks "command" build backend seems to achieve it by just copying entire files under lua-aws to rocks directory, through it breaks some portability (especially windows). 
 - if so, I want to revert the change. because with this change, we force user to use lua-aws with luarocks installation. I also use lua-aws without installation (part of luact)

@CriztianiX how do you think?

### CODE REVIEW

**Comment by CriztianiX** [comment]
Like you said in point one, if we follow the specification of rockspec dkjson it should be treated as a dependency. We might have to perform some checks in our library about the installed version (?).
Another question, dkjson  was modified ? If yes, there will be a cleaner option for this?

The lowest point is the point 2. Because as you've told us rockspec installed on his directory our services. 

So... i made this commit and seems works fine for me...
https://github.com/CriztianiX/lua-aws/commit/a7e978d31b2f0a8368d83717fc4e134ea21ac22e

What do you think?

**Comment by umegaya** [comment]
hi, I still think we should manage our JSON parser version. even if currently dkjson.lua is not modified (I think its vanilla 2.3). it is just my preference that I want to manage dependency by ourselves.

and the reason is mainly
1. I don't prefer to do NxM checks of dependent library x lua-aws version (and it means sometimes we decide to deprecate old versions), if dkjson have some upgrade until now.
2. yes, dkjson already has enough functionality so it is not likely to upgrade version. but it may contain unknown bug and it cause lua-aws bug after more features are implemented to it. in such case, I want to provide fix without making PR to dkjson project and waiting for applying it at luarocks. 
(it may sound like imaginary fear. but remember [lua-wiki's sha2 code contains bug](http://lua-users.org/cgi-bin/wiki.pl?action=history&id=SecureHashAlgorithm) until a few month ago)
3. dkjson provides "JSON parser". that is, it has standard, well-defined behavior. then fixing bug is easy, no need to wait for original author fix it. also it is likely that we replace it with better implementation. so I think this is not strict dependency.

I will not stop upgrade of dkjson version if it is worthy to do, also I understand the opinion that we should obey the standard way of luarocks. but I believe that managing dependency by ourselves, have enough merit in *this* case. 

I can not come up with cleaner way of managing our dependency of dkjson. put it in *deps* folder is my best idea now. do you have any ideas?

**Comment by CriztianiX** [comment]
Hey... your opinions sounds good.

**Comment by CriztianiX** [comment]
https://github.com/CriztianiX/lua-aws/commit/c259f5d908770f0ec304084fbc7dcfde9f920ba5

**Comment by umegaya** [comment]
same contents merge with #11, so I close this PR

**Pull request closed without merging**
